/**
 * Complete exercise library with sub-muscle targeting,
 * multiple muscles, full guides, common mistakes, stretching
 */

export const EXERCISE_DB = [
  // ── CHEST ─────────────────────────────────────────────────────────
  { id:'bp-flat', gifUrl:'https://v2.exercisedb.io/image/0025', name:'Barbell Bench Press', category:'Chest', sub:'Mid Chest',
    primary:'Pectoralis Major (Sternal)', secondary:['Anterior Deltoid','Triceps Brachii'], other:['Serratus Anterior','Coracobrachialis'],
    level:'Intermediate', equipment:'Barbell', type:'compound', shape:'barbell',
    muscles_visual:['chest','front-delt','triceps'],
    sets:'4 × 5-8 reps', rest:'2-3 min', tempo:'2-1-1',
    steps:['Lie flat, eyes under bar. Grip just outside shoulder-width.','Retract scapulae and create upper-back arch - feet flat.','Unrack, lower bar to mid-sternum at 45° elbow flare.','Touch chest lightly, drive bar back up explosively.','Lock out fully, repeat without losing tension.'],
    mistakes:['Flaring elbows 90° - stresses shoulder joint','Bouncing bar off chest - lose tension and risk injury','Losing back arch - reduces range and power','Bar drifting toward face - path should be slightly diagonal'],
    tips:'Imagine bending the bar into a U shape. Initiate with your lats before pressing.',
    cues:['Chest up','Elbows 45°','Drive the floor'],
  },
  { id:'bp-incline', gifUrl:'https://v2.exercisedb.io/image/0660', name:'Incline Dumbbell Press', category:'Chest', sub:'Upper Chest',
    primary:'Pectoralis Major (Clavicular)', secondary:['Anterior Deltoid','Triceps'], other:['Serratus Anterior'],
    level:'Beginner', equipment:'Dumbbells', type:'compound', shape:'dumbbell',
    sets:'3-4 × 8-12 reps', rest:'90 sec', tempo:'2-0-1',
    steps:['Set bench 30-45°. Dumbbells at chest level, neutral grip.','Press up and slightly together, exhale on effort.','Lower slowly to full stretch - feel upper chest stretch.','Do not let elbows flare past 90°.'],
    mistakes:['Bench too steep (>45°) shifts work to shoulders','Not going to full stretch - cuts range of motion','Wrists bent back - keep them stacked over elbows'],
    tips:'30° incline targets upper chest. 45° starts shifting to front delt.',
  },
  { id:'cable-fly', gifUrl:'https://v2.exercisedb.io/image/1271', name:'Cable Chest Fly', category:'Chest', sub:'Inner Chest',
    primary:'Pectoralis Major (inner fibers)', secondary:['Anterior Deltoid'], other:['Biceps (minor)'],
    level:'Beginner', equipment:'Cable Machine', type:'isolation', shape:'cables',
    sets:'3 × 12-15 reps', rest:'60 sec', tempo:'2-1-2',
    steps:['Stand center of cable station, cables at chest height.','Lean slightly forward, slight bend in elbows (keep fixed).','Bring hands together in wide arc - squeeze hard at center.','Hold 1 second, return slowly feeling stretch.'],
    mistakes:['Bending elbows too much - becomes a press','Going too fast - lose the stretch benefit','Not squeezing at the top - miss the peak contraction'],
    tips:'The advantage over dumbbells: constant tension through full range. Go lighter than you think.',
  },
  { id:'dips-chest', gifUrl:'https://v2.exercisedb.io/image/0207', name:'Chest Dips', category:'Chest', sub:'Lower Chest',
    primary:'Pectoralis Major (Lower)', secondary:['Triceps','Anterior Deltoid'], other:['Rhomboids (minor)'],
    level:'Intermediate', equipment:'Parallel Bars', type:'compound', shape:'dip',
    sets:'3 × 8-15 reps', rest:'90 sec', tempo:'3-0-1',
    steps:['Grip bars, lean forward 30° - this targets chest over triceps.','Lower until upper arms parallel, feel deep chest stretch.','Drive up explosively, lean maintained.','Cross feet behind you for stability.'],
    mistakes:['Staying vertical - shifts all work to triceps','Insufficient depth - limits chest activation','Rushing - take 3 seconds to lower'],
    tips:'Weighted dips are one of the most effective chest builders. Add weight via dip belt when bodyweight becomes easy.',
  },

  // ── BACK ──────────────────────────────────────────────────────────
  { id:'deadlift', gifUrl:'https://v2.exercisedb.io/image/0032', name:'Conventional Deadlift', category:'Back', sub:'Erector Spinae',
    primary:'Erector Spinae', secondary:['Glutes','Hamstrings','Trapezius'], other:['Lats','Core','Forearms'],
    level:'Advanced', equipment:'Barbell', type:'compound', shape:'barbell',
    sets:'3-5 × 3-5 reps', rest:'3-4 min', tempo:'1-0-1',
    steps:['Bar over mid-foot. Hip-width stance, toes slightly out.','Hinge: hips back, grip bar just outside legs, chest up.','Brace core max, engage lats (protect armpits from wind).','Drive floor away - hips and chest rise together.','Lock out hips and knees simultaneously at top.'],
    mistakes:['Rounding lower back - herniation risk under heavy load','Bar drifting from body - loses mechanical advantage','Jerking the bar - build tension before you pull','Hyperextending at lockout - compresses lumbar spine'],
    tips:'Think: leg press the floor. Bar stays in contact with shins. Never reset tension between reps for maximum sets.',
    cues:['Chest up','Lats in','Push floor'],
  },
  { id:'pullup', gifUrl:'https://v2.exercisedb.io/image/0651', name:'Pull-Up', category:'Back', sub:'Lats',
    primary:'Latissimus Dorsi', secondary:['Biceps Brachii','Rear Deltoid','Rhomboids'], other:['Teres Major','Infraspinatus'],
    level:'Intermediate', equipment:'Pull-up Bar', type:'compound', shape:'pullup',
    sets:'3-4 × 5-12 reps', rest:'2 min', tempo:'2-1-2',
    steps:['Dead hang, overhand grip shoulder-width (or slightly wider).','Retract scapulae FIRST - this initiates with lats not arms.','Pull elbows toward hip pockets - chest to bar.','Control the descent - 2-3 seconds - max lat stretch.'],
    mistakes:['Pulling with biceps first - reduces lat activation','Kipping - wastes the eccentric phase','Not achieving full dead hang - limits range','Chin barely over bar - go chest to bar'],
    tips:'Imagine you\'re trying to put your elbows in your back pockets. If you can do 12+ easily, add weight.',
  },
  { id:'bent-row', gifUrl:'https://v2.exercisedb.io/image/0086', name:'Barbell Bent-Over Row', category:'Back', sub:'Middle Traps',
    primary:'Rhomboids & Mid Traps', secondary:['Lats','Biceps'], other:['Erector Spinae','Rear Delt'],
    level:'Intermediate', equipment:'Barbell', type:'compound', shape:'barbell',
    sets:'4 × 8-10 reps', rest:'2 min', tempo:'1-1-2',
    steps:['Hip hinge: 45° torso, flat back, knees slightly bent.','Overhand grip, bar hanging from straight arms.','Pull bar to lower ribcage, drive elbows to ceiling.','Squeeze shoulder blades at top for 1 second.','Lower with control - full stretch.'],
    mistakes:['Upright torso - becomes a shrug','Rounding back under load - spinal risk','Using momentum/heaving - reduces time under tension'],
    tips:'Pull elbows, not hands. The hands are just hooks.',
  },
  { id:'face-pull', gifUrl:'https://v2.exercisedb.io/image/0342', name:'Face Pull', category:'Back', sub:'Upper Traps',
    primary:'Rear Deltoid & Upper Traps', secondary:['Rhomboids','External Rotators'], other:['Infraspinatus','Teres Minor'],
    level:'Beginner', equipment:'Cable Machine', type:'isolation', shape:'cables',
    sets:'3-4 × 15-20 reps', rest:'60 sec', tempo:'1-1-2',
    steps:['Cable at face height with rope. Light weight.','Pull rope to face - split rope, hands beside ears.','External rotate at end: elbows high, hands behind ears.','Hold 1 second, return slowly.'],
    mistakes:['Going too heavy - loses external rotation','Elbows dropping below shoulder height','Pulling to chin instead of face'],
    tips:'Arguably the most important exercise for shoulder health. Do it every session. High reps, light weight.',
  },

  // ── SHOULDERS ─────────────────────────────────────────────────────
  { id:'ohp', gifUrl:'https://v2.exercisedb.io/image/0526', name:'Overhead Press', category:'Shoulders', sub:'Front Delts',
    primary:'Anterior Deltoid', secondary:['Lateral Deltoid','Triceps','Upper Pecs'], other:['Serratus Anterior','Trapezius','Core'],
    level:'Intermediate', equipment:'Barbell', type:'compound', shape:'barbell',
    sets:'4 × 5-8 reps', rest:'2-3 min', tempo:'2-1-1',
    steps:['Bar at upper chest, grip just outside shoulders.','Brace core and glutes hard - protect lower back.','Press bar directly overhead - lock arms fully.','Bar should travel in straight line - tuck chin on way up.','Lower to starting position with control.'],
    mistakes:['Excessive lumbar arch - compresses spine','Bar drifting forward - loses efficiency','Flared elbows (behind bar)','Not achieving full overhead lockout'],
    tips:'The overhead press is a full-body stability challenge. Weak core = weaker press. Brace like you\'re taking a punch.',
  },
  { id:'lateral-raise', gifUrl:'https://v2.exercisedb.io/image/0440', name:'Lateral Raise', category:'Shoulders', sub:'Side Delts',
    primary:'Lateral Deltoid', secondary:['Supraspinatus','Anterior Deltoid (minor)'], other:['Upper Traps'],
    level:'Beginner', equipment:'Dumbbells', type:'isolation', shape:'dumbbell',
    sets:'4 × 12-20 reps', rest:'60 sec', tempo:'2-1-3',
    steps:['Stand, dumbbells at sides. Slight forward lean (10°).','Raise arms to just below shoulder height - no higher.','Lead with elbows, pinky slightly higher than thumb.','3-second SLOW lower - this is where the muscle grows.','Pause 1 second at sides before repeating.'],
    mistakes:['Swinging/using momentum - traps and momentum lift the weight','Going above shoulder height - traps take over','Lowering too fast - loses eccentric phase','Thumbs higher than pinkies - shifts to front delt'],
    tips:'Go embarrassingly light. 5-8kg is enough if done correctly. The lateral delt is a small muscle - isolate it properly.',
  },
  { id:'rear-delt-fly', gifUrl:'https://v2.exercisedb.io/image/0614', name:'Rear Delt Fly', category:'Shoulders', sub:'Rear Delts',
    primary:'Posterior Deltoid', secondary:['Rhomboids','Middle Traps'], other:['Infraspinatus','Teres Minor'],
    level:'Beginner', equipment:'Dumbbells', type:'isolation', shape:'dumbbell',
    sets:'3-4 × 15-20 reps', rest:'60 sec', tempo:'2-1-2',
    steps:['Seated: bend 90° forward, arms hanging. Or lying face-down on incline bench.','Raise arms out to sides, slight elbow bend (fixed).','Squeeze rear delts at top - pinch shoulder blades.','Lower with control - no swinging.'],
    mistakes:['Too much weight - traps dominate','Not going heavy enough to actually challenge rear delts','Bending elbows too much - becomes a row'],
    tips:'Most people have underdeveloped rear delts. This creates rounded shoulders and injury risk. Prioritize this exercise.',
  },

  // ── ARMS ──────────────────────────────────────────────────────────
  { id:'barbell-curl', gifUrl:'https://v2.exercisedb.io/image/0035', name:'Barbell Bicep Curl', category:'Arms', sub:'Biceps',
    primary:'Biceps Brachii (long + short head)', secondary:['Brachialis'], other:['Brachioradialis','Forearm Flexors'],
    level:'Beginner', equipment:'Barbell', type:'isolation', shape:'barbell',
    sets:'3-4 × 8-12 reps', rest:'75 sec', tempo:'1-1-3',
    steps:['Stand, underhand shoulder-width grip, arms extended.','Pin elbows to sides - they must not move.','Curl bar toward chin in smooth arc.','Squeeze hard at top - supinate wrists.','Lower in 3 seconds - full extension.'],
    mistakes:['Swinging back - back takes the load','Elbows drifting forward - decreases peak contraction','Not going to full extension - limits range','Partial reps at the top only'],
    tips:'The 3-second lower is where most of the growth happens. Don\'t cheat the descent.',
  },
  { id:'hammer-curl', gifUrl:'https://v2.exercisedb.io/image/0399', name:'Hammer Curl', category:'Arms', sub:'Brachialis',
    primary:'Brachialis (underneath bicep)', secondary:['Brachioradialis','Biceps Brachii'], other:['Forearm Extensors'],
    level:'Beginner', equipment:'Dumbbells', type:'isolation', shape:'dumbbell',
    sets:'3 × 10-14 reps', rest:'60 sec', tempo:'1-1-2',
    steps:['Neutral grip (palms facing each other). Elbows pinned.','Curl up - maintain neutral wrist throughout.','Squeeze at top, lower with control.','Can be done alternating or both arms.'],
    mistakes:['Rotating wrist during movement','Letting elbows drift forward','Using excessive momentum'],
    tips:'Brachialis grows underneath the bicep, pushing it up. Essential for arm thickness and that "popped" look.',
  },
  { id:'tricep-pushdown', gifUrl:'https://v2.exercisedb.io/image/0697', name:'Tricep Cable Pushdown', category:'Arms', sub:'Triceps',
    primary:'Triceps Brachii (Lateral Head)', secondary:['Medial Head','Long Head'], other:['Anconeus'],
    level:'Beginner', equipment:'Cable Machine', type:'isolation', shape:'cables',
    sets:'3-4 × 12-15 reps', rest:'60 sec', tempo:'1-1-2',
    steps:['High cable, straight bar or rope. Elbows pinned at sides.','Push bar down to full extension - flex triceps hard.','Elbows remain stationary throughout.','Allow slow return to 90°, feel stretch.'],
    mistakes:['Letting elbows rise - turns into a row','Leaning over the bar - uses bodyweight not muscle','Not achieving full extension - misses peak contraction'],
    tips:'Rope allows wrists to separate at bottom - greater range and contraction. Try both versions.',
  },
  { id:'close-grip-bench', gifUrl:'https://v2.exercisedb.io/image/0105', name:'Close-Grip Bench Press', category:'Arms', sub:'Triceps',
    primary:'Triceps Brachii (all 3 heads)', secondary:['Pectoralis Major (inner)','Anterior Deltoid'], other:['Anconeus'],
    level:'Intermediate', equipment:'Barbell', type:'compound', shape:'barbell',
    sets:'3-4 × 6-10 reps', rest:'2 min', tempo:'2-1-1',
    steps:['Grip shoulder-width or slightly inside. Flat bench.','Keep elbows tucked close to torso as you lower.','Lower to lower chest - controlled descent.','Press with focus on triceps extending.'],
    mistakes:['Grip too close - wrist pain risk','Flaring elbows - loses tricep emphasis','Lowering to upper chest instead of lower chest'],
    tips:'Best compound exercise for overall tricep mass. Heavier than isolation work.',
  },
  { id:'forearm-curl', gifUrl:'https://v2.exercisedb.io/image/0248', name:'Wrist Curl (Forearms)', category:'Arms', sub:'Forearms',
    primary:'Wrist Flexors (Flexor Carpi Radialis/Ulnaris)', secondary:['Finger Flexors'], other:['Pronator Teres'],
    level:'Beginner', equipment:'Dumbbells', type:'isolation', shape:'dumbbell',
    sets:'3 × 15-20 reps', rest:'45 sec', tempo:'1-1-2',
    steps:['Seated, forearms resting on thighs, wrists over knees.','Underhand grip. Let weight roll to fingertips.','Curl wrists up fully, squeeze at top.','Reverse: overhand for wrist extensors.'],
    mistakes:['Using too much weight - full range impossible','Forearms lifting off thighs - wrong movement pattern'],
    tips:'Forearm training improves grip strength which directly increases deadlift, row, and pulldown weights.',
  },

  // ── LEGS ──────────────────────────────────────────────────────────
  { id:'back-squat', gifUrl:'https://v2.exercisedb.io/image/0685', name:'Back Squat', category:'Legs', sub:'Quads',
    primary:'Quadriceps (all 4 heads)', secondary:['Glutes','Hamstrings','Adductors'], other:['Erector Spinae','Core','Calves'],
    level:'Intermediate', equipment:'Barbell', type:'compound', shape:'barbell',
    sets:'4-5 × 5-8 reps', rest:'3 min', tempo:'3-1-1',
    steps:['Bar on traps (high bar) or rear delts (low bar). Shoulder-width stance.','Brace core, take a breath of air.','Break at hips and knees simultaneously - sit back and down.','Knees track over toes. Depth: crease of hip below knee.','Drive through full foot, push knees out, stand tall.'],
    mistakes:['Knees caving inward (valgus collapse) - knee ligament stress','Heels rising - limited ankle mobility or stance too narrow','Forward lean excessive - shifts to back (use low bar or fix mobility)','Depth not achieved - partial reps don\'t count'],
    tips:'High bar = more quad. Low bar = more posterior chain. Both are valid. Fix ankle mobility if heels rise.',
    cues:['Knees out','Chest up','Drive floor'],
  },
  { id:'rdl', gifUrl:'https://v2.exercisedb.io/image/0629', name:'Romanian Deadlift', category:'Legs', sub:'Hamstrings',
    primary:'Hamstrings (Biceps Femoris, Semitendinosus)', secondary:['Glutes','Erector Spinae'], other:['Adductors','Core'],
    level:'Intermediate', equipment:'Barbell', type:'compound', shape:'barbell',
    sets:'3-4 × 8-12 reps', rest:'2 min', tempo:'3-1-1',
    steps:['Stand tall, hip-width, overhand grip outside legs.','Push hips back - not down. Slight knee bend (fixed).','Bar drags down legs as you hinge - feel hamstring stretch.','Stop when back starts to round - that\'s your end range.','Drive hips forward to stand - squeeze glutes at top.'],
    mistakes:['Bending knees like a squat - this is a hip hinge','Rounding lower back under load - injury risk','Not feeling the hamstring stretch - either too heavy or squatting'],
    tips:'The stretch at the bottom is the point. If you don\'t feel it in your hamstrings, you\'re not doing it right.',
  },
  { id:'hip-thrust', gifUrl:'https://v2.exercisedb.io/image/1320', name:'Hip Thrust', category:'Legs', sub:'Glutes',
    primary:'Gluteus Maximus', secondary:['Hamstrings','Adductors'], other:['Erector Spinae','Core'],
    level:'Beginner', equipment:'Barbell', type:'compound', shape:'body',
    sets:'3-4 × 10-15 reps', rest:'90 sec', tempo:'1-2-2',
    steps:['Upper back on bench. Bar over hip crease - use pad.','Plant feet flat, hip-width, knees at 90° at top.','Drive hips up until torso parallel to floor.','Squeeze glutes hard at top - hold 2 seconds.','Lower without touching floor - keep tension.'],
    mistakes:['Not squeezing at top - loses the purpose','Hyperextending lower back - lumbar strain','Feet too far or close - changes muscle emphasis'],
    tips:'Arguably the best glute exercise. Women should especially prioritize this. Go heavy - glutes are a big muscle.',
  },
  { id:'leg-curl', gifUrl:'https://v2.exercisedb.io/image/0464', name:'Lying Leg Curl', category:'Legs', sub:'Hamstrings',
    primary:'Biceps Femoris (Short Head)', secondary:['Semitendinosus','Semimembranosus'], other:['Gastrocnemius (minor)'],
    level:'Beginner', equipment:'Machine', type:'isolation', shape:'machine',
    sets:'3 × 10-15 reps', rest:'75 sec', tempo:'1-1-3',
    steps:['Lying face down, pad just above ankles. Hips flat.','Curl legs to full flexion - heels to glutes.','Hold briefly at top, feet flexed (dorsiflexed).','Lower in 3 seconds - full extension.'],
    mistakes:['Hips rising off pad - hip flexors helping','Not achieving full ROM - partial reps','Lowering too fast - misses eccentric'],
    tips:'Dorsiflexing your feet (toes toward shins) at the top increases hamstring activation by 20%.',
  },
  { id:'calf-raise', gifUrl:'https://v2.exercisedb.io/image/1367', name:'Standing Calf Raise', category:'Legs', sub:'Calves',
    primary:'Gastrocnemius', secondary:['Soleus'], other:['Tibialis Posterior'],
    level:'Beginner', equipment:'Machine', type:'isolation', shape:'machine',
    sets:'4 × 15-25 reps', rest:'60 sec', tempo:'1-2-3',
    steps:['Balls of feet on edge. Full hang at bottom - stretch.','Rise to full height on balls of feet - squeeze hard.','Hold 2 seconds at top.','Lower SLOWLY - 3 seconds - deep stretch.'],
    mistakes:['Bouncing - no stretch benefit','Short range of motion','Going too fast - misses stretch and contraction','Not holding at the top'],
    tips:'Calves are notoriously stubborn. They need HIGH reps, full ROM, and slow tempo to grow.',
  },

  // ── CORE ──────────────────────────────────────────────────────────
  { id:'cable-crunch', gifUrl:'https://v2.exercisedb.io/image/0193', name:'Cable Crunch', category:'Core', sub:'Abs',
    primary:'Rectus Abdominis', secondary:['Obliques (minor)'], other:['Hip Flexors (if going too far)'],
    level:'Beginner', equipment:'Cable Machine', type:'isolation', shape:'cables',
    sets:'3-4 × 12-20 reps', rest:'60 sec', tempo:'1-1-2',
    steps:['Kneel facing high cable with rope. Hold rope at sides of face.','This is SPINAL FLEXION - curl chest to pelvis, not hips to floor.','Contract abs hard at bottom - pause.','Return slowly, keeping abs tense throughout.'],
    mistakes:['Hip hinge movement instead of spinal flexion','Going too heavy - hip flexors dominate','Not keeping rope fixed at face level'],
    tips:'Abs need load to grow just like any muscle. This is their equivalent of the bench press.',
  },
  { id:'plank', gifUrl:'https://v2.exercisedb.io/image/0575', name:'Plank', category:'Core', sub:'Transverse Abdominis',
    primary:'Transverse Abdominis (TVA)', secondary:['Rectus Abdominis','Obliques'], other:['Glutes','Erector Spinae','Serratus'],
    level:'Beginner', equipment:'Bodyweight', type:'isolation', shape:'body',
    sets:'3 × 30-60 sec', rest:'60 sec', tempo:'hold',
    steps:['Elbows directly under shoulders. Forearms flat.','Squeeze everything: abs, glutes, quads, lats simultaneously.','Hips level - neither sagging nor too high.','Breathe steadily - don\'t hold breath.','Keep neck neutral - don\'t look up.'],
    mistakes:['Hips sagging - lower back under stress','Holding breath','Head dropping or craning up','Only bracing abs - forgetting glutes'],
    tips:'A 30-second perfect plank beats a 2-minute sloppy one every time. Quality over duration.',
  },
  { id:'russian-twist', gifUrl:'https://v2.exercisedb.io/image/0635', name:'Russian Twist', category:'Core', sub:'Obliques',
    primary:'Internal & External Obliques', secondary:['Rectus Abdominis'], other:['Hip Flexors'],
    level:'Beginner', equipment:'Bodyweight', type:'isolation', shape:'body',
    sets:'3 × 20-30 reps (each side)', rest:'60 sec', tempo:'controlled',
    steps:['Sit 45° lean, knees bent, feet slightly off floor.','Clasp hands or hold weight. Keep spine tall.','Rotate torso: touch hands to floor on each side.','Focus on oblique contraction, not just arm movement.'],
    mistakes:['Rotating arms not torso - neck/shoulder movement','Letting feet touch floor - reduces core demand','Rounding spine - puts discs at risk under load'],
    tips:'Adding a weight plate or medicine ball increases oblique challenge significantly.',
  },
  { id:'leg-raise', gifUrl:'https://v2.exercisedb.io/image/1460', name:'Hanging Leg Raise', category:'Core', sub:'Abs',
    primary:'Lower Rectus Abdominis', secondary:['Hip Flexors','Obliques'], other:['Forearms (grip)'],
    level:'Intermediate', equipment:'Pull-up Bar', type:'compound', shape:'pullup',
    sets:'3 × 10-15 reps', rest:'75 sec', tempo:'2-1-2',
    steps:['Hang from bar. Control any swing before starting.','Raise legs to 90° - keep legs straight for max intensity.','Tilt pelvis BACK at the top - this engages lower abs.','Lower with control - don\'t swing.'],
    mistakes:['Swinging to create momentum','Not tilting pelvis - hip flexors do all the work','Bent knees (easier - reduce if needed as progression)'],
    tips:'The posterior pelvic tilt at the top is what separates ab work from hip flexor work.',
  },
]

// ── STRETCHING ROUTINES ────────────────────────────────────────────────────

export const STRETCHING = {
  Chest: [
    { name:'Doorway Chest Stretch', duration:'30-45 sec each side', steps:['Place forearm on doorframe at 90°','Step through, rotate body away until chest feels stretch','Hold - breathe into stretch'], muscles:'Pectoralis Major, Anterior Deltoid, Biceps' },
    { name:'Cross-Body Shoulder Stretch', duration:'30 sec each', steps:['Pull arm across chest with opposite hand','Keep shoulder down - not shrugging','Feel stretch in rear shoulder'], muscles:'Posterior Deltoid, Rhomboids' },
    { name:'Overhead Tricep Stretch', duration:'30 sec each', steps:['Arm overhead, elbow bent','Push elbow back with opposite hand','Hold and breathe'], muscles:'Triceps, Latissimus Dorsi' },
  ],
  Back: [
    { name:'Child\'s Pose', duration:'60 sec', steps:['Kneel, sit back toward heels','Reach arms forward, forehead to floor','Let low back release - breathe into it'], muscles:'Erector Spinae, Lats, Glutes' },
    { name:'Cat-Cow', duration:'10 reps slow', steps:['All-fours. Inhale: drop belly, arch back, look up','Exhale: round spine, tuck chin and tailbone','Flow smoothly'], muscles:'Entire Spine, Core' },
    { name:'Lat Stretch on Pole/Bar', duration:'30 sec each', steps:['Grab bar at arm height, step back until arm straight','Lean away from bar - feel lat lengthening','Can rotate to bias different lat fibers'], muscles:'Latissimus Dorsi, Teres Major' },
  ],
  Legs: [
    { name:'Standing Quad Stretch', duration:'30 sec each', steps:['Stand on one foot, pull other heel to glutes','Keep knees together','Push hips slightly forward for deeper stretch'], muscles:'Quadriceps, Hip Flexors' },
    { name:'Pigeon Pose (Hip Flexors/Glutes)', duration:'60 sec each', steps:['From all-fours: bring one knee forward behind hand','Extend rear leg behind. Sink hips toward floor','For deeper stretch: fold forward over front shin'], muscles:'Piriformis, Glutes, Hip Flexors, IT Band' },
    { name:'Romanian Deadlift Stretch', duration:'5 reps slow', steps:['Hinge forward with flat back, soft knees','Go until hamstrings are at limit','Breathe at bottom - let muscle release'], muscles:'Hamstrings, Glutes, Erector Spinae' },
    { name:'Seated Calf Stretch', duration:'30 sec each', steps:['Sit, extend leg, loop towel around ball of foot','Gently pull foot toward shin','Feel stretch along entire calf and Achilles'], muscles:'Gastrocnemius, Soleus, Achilles Tendon' },
  ],
  Shoulders: [
    { name:'Chest Opener (Clasped Hands Behind)', duration:'30 sec', steps:['Stand tall, clasp hands behind back','Squeeze shoulder blades, open chest to ceiling','Hold at comfortable edge'], muscles:'Pectoralis Minor, Anterior Deltoid, Biceps' },
    { name:'Cross-Body Stretch', duration:'30 sec each', steps:['Pull arm across chest low (for posterior capsule)','Use other arm to maintain position','Feel in back of shoulder'], muscles:'Posterior Deltoid, Infraspinatus, Teres Minor' },
    { name:'Wall Slide', duration:'10 reps', steps:['Back against wall, arms in W position (elbows bent, back)','Slide arms up to Y position while keeping contact with wall','Return slowly'], muscles:'Lower Traps, Serratus Anterior, Rotator Cuff' },
  ],
  Arms: [
    { name:'Wrist Flexor Stretch', duration:'30 sec each', steps:['Arm extended, palm up','With other hand, gently pull fingers back toward body','Feel stretch along underside of forearm'], muscles:'Wrist Flexors, Forearm Flexors' },
    { name:'Bicep Wall Stretch', duration:'30 sec each', steps:['Stand beside wall, place hand on wall at shoulder height','Slowly rotate body away from wall until bicep stretches','Hold at comfortable edge'], muscles:'Biceps Brachii, Anterior Deltoid' },
    { name:'Tricep Overhead Stretch', duration:'30 sec each', steps:['Raise arm overhead, bend elbow behind head','Push elbow back with opposite hand','Feel stretch along back of upper arm'], muscles:'Triceps (Long Head especially)' },
  ],
  Core: [
    { name:'Cobra / Sphinx', duration:'30-45 sec', steps:['Lie face down, hands under shoulders','Press up, keep hips on floor','Hold - feel stretch across entire abdomen'], muscles:'Rectus Abdominis, Internal Obliques, Hip Flexors' },
    { name:'Seated Forward Fold', duration:'60 sec', steps:['Sit with legs extended (or crossed)','Hinge forward at hips - NOT rounding back','Reach forward, breathe at deepest point'], muscles:'Hamstrings, Erector Spinae, Calves' },
    { name:'Side Bend', duration:'30 sec each', steps:['Stand tall or seated, raise one arm overhead','Lean smoothly to opposite side','Feel long stretch along entire side of torso'], muscles:'Internal/External Obliques, Quadratus Lumborum, Lats' },
  ],
  Cardio: [
    { name:'Hip Flexor Lunge Stretch', duration:'45 sec each', steps:['Low lunge: rear knee on floor','Push hips forward and down','Raise arms overhead for deeper stretch'], muscles:'Psoas, Iliacus, Rectus Femoris' },
    { name:'Standing Hamstring Sweep', duration:'10 reps each', steps:['Stand on one leg, extend other leg on slight elevation','Hinge forward gently - keep back flat','Feel hamstring lengthen - don\'t bounce'], muscles:'Hamstrings, Gastrocnemius' },
    { name:'Ankle Circles', duration:'30 sec each direction', steps:['Lift foot, rotate ankle in full circles','10 circles each direction','Slow and controlled'], muscles:'Ankle Joint Mobility, Calf Complex' },
  ],
}

/**
 * Warmup routines per muscle group
 * Goal: increase blood flow, activate muscles, prepare joints
 */
export const WARMUP = {
  Chest: [
    { name:'Arm Circles', duration:'30 sec each direction', sets:'2',
      steps:['Stand tall, extend arms out to sides','Make large slow circles forward 10 reps','Reverse direction 10 reps','Gradually increase speed on 2nd round'],
      why:'Lubricates shoulder joint, warms rotator cuff before pressing movements' },
    { name:'Band Pull-Apart (or no-band)', duration:'15 reps x 3',
      steps:['Hold band or clasp hands in front at chest height','Pull hands apart squeezing shoulder blades','Hold 1 second, return controlled','Keep arms straight throughout'],
      why:'Activates rear delts and rhomboids to stabilize shoulders during chest pressing' },
    { name:'Push-Up (slow tempo)', duration:'8-10 reps x 2',
      steps:['Standard push-up position','Lower in 3 seconds, pause 1 second at bottom','Push back up explosively','Focus on feeling chest stretch at bottom'],
      why:'Primes chest, triceps and shoulders with a bodyweight pattern before loading' },
  ],
  Back: [
    { name:'Cat-Cow Spine Warmup', duration:'10 slow reps',
      steps:['All-fours position, wrists under shoulders','Inhale: drop belly, lift chest and tailbone (cow)','Exhale: round spine toward ceiling (cat)','Move slowly and breathe deeply'],
      why:'Mobilizes the entire spine and activates the erector muscles before pulling movements' },
    { name:'Dead Hang', duration:'20-30 sec x 2',
      steps:['Hang from pull-up bar with straight arms','Let shoulders fully elevate (passive hang)','Breathe and relax the grip slightly','Step down, shake out hands'],
      why:'Decompresses spine, stretches lats and opens shoulder girdle before rows and pull-ups' },
    { name:'Scapular Pull-Ups', duration:'10 reps x 2',
      steps:['Hang from bar, arms straight','Without bending elbows, pull shoulder blades DOWN','Feel lats engage - body rises slightly','Lower back to dead hang, repeat'],
      why:'Teaches lat activation pattern and warms up the scapular stabilizers' },
  ],
  Shoulders: [
    { name:'Wall Slides', duration:'10 reps x 2',
      steps:['Back against wall, arms in W shape (elbows bent 90°)','Slowly slide arms up wall to Y shape, maintaining contact','Return slowly to W','Keep lower back flat against wall throughout'],
      why:'Activates lower traps and serratus anterior - critical stabilizers for overhead pressing' },
    { name:'Cuban Press (light or no weight)', duration:'10 reps x 2',
      steps:['Hold dumbbells or just mimic the motion','Start with arms at sides, palms back','Row elbows up to shoulder height','Externally rotate so knuckles point up','Press overhead then reverse the motion'],
      why:'Comprehensively warms up all 3 delt heads and the rotator cuff in one movement' },
    { name:'Cross-Body Shoulder Swing', duration:'20 reps each arm',
      steps:['Stand with arm hanging loose','Swing arm across body then out to side in a pendulum','Gradually increase range each swing','Keep shoulder relaxed, not tense'],
      why:'Gently mobilizes the glenohumeral joint and increases synovial fluid production' },
  ],
  Arms: [
    { name:'Wrist Circles', duration:'20 sec each direction',
      steps:['Extend arms forward, palms down','Rotate wrists in full circles - slow and controlled','10 circles clockwise, 10 counter-clockwise','Spread fingers wide at bottom of each circle'],
      why:'Prepares wrist joint for curls, presses and any gripping movements' },
    { name:'Resistance Band Bicep Curl (light)', duration:'15 reps x 2',
      steps:['Use very light band or no weight at all','Full range curl with slow 3-second lower','Focus on feeling the bicep stretch at the bottom','No swinging - strict form only'],
      why:'Increases blood flow to biceps and elbow tendons before heavier loading' },
    { name:'Tricep Extensions (bodyweight/light)', duration:'12 reps x 2',
      steps:['Overhead tricep extension with light weight or no weight','Full range - feel the stretch at the top','Lock out fully at the bottom','Move slowly on the lowering phase'],
      why:'Warms the elbow joint and prepares the long head of the tricep which crosses the shoulder' },
  ],
  Legs: [
    { name:'Leg Swings', duration:'15 each direction x each leg',
      steps:['Hold wall for balance, stand on one leg','Swing free leg forward and back - controlled pendulum','Gradually increase range over 10 reps','Switch to side-to-side swings'],
      why:'Dynamically mobilizes the hip joint and warms hip flexors, glutes and hamstrings' },
    { name:'Bodyweight Squat (slow)', duration:'10 reps x 2',
      steps:['Feet shoulder-width, toes slightly out','Lower in 3 seconds - focus on depth','Hold at bottom 1 second','Drive up through full foot'],
      why:'Primes quad, glute and hamstring activation patterns and warms the knee joint' },
    { name:'Glute Bridge', duration:'15 reps x 2',
      steps:['Lie on back, knees bent, feet flat','Drive hips up squeezing glutes hard','Hold at top 2 seconds - full hip extension','Lower slowly without touching floor'],
      why:'Activates glutes before squats and deadlifts - crucial for posterior chain protection' },
    { name:'Walking Lunges', duration:'10 each leg',
      steps:['Step forward into a deep lunge','Lower back knee toward floor','Push off front foot to bring feet together','Step forward with other leg'],
      why:'Warms quads, glutes, hip flexors and improves balance before leg session' },
  ],
  Core: [
    { name:'Dead Bug', duration:'10 reps each side x 2',
      steps:['Lie on back, arms straight up, knees bent 90° (tabletop)','Press lower back INTO the floor - maintain this throughout','Slowly lower opposite arm and leg toward floor','Return, repeat other side - never lose back contact'],
      why:'Activates the transverse abdominis (deep core stabilizer) before loaded core work' },
    { name:'Bird Dog', duration:'10 reps each side x 2',
      steps:['All-fours position, neutral spine','Extend opposite arm and leg simultaneously','Hold 2 seconds - squeeze glute and shoulder blade','Return, repeat other side - no hip rotation'],
      why:'Trains anti-rotation stability and activates erectors, glutes and core together' },
    { name:'Supine Pelvic Tilts', duration:'15 reps',
      steps:['Lie on back, knees bent','Flatten lower back by tilting pelvis up (posterior tilt)','Hold 2 seconds, release to neutral','Never arch excessively - small controlled movement'],
      why:'Teaches proper pelvic positioning and activates the deep core before ab exercises' },
  ],
  Cardio: [
    { name:'March in Place', duration:'60 seconds',
      steps:['Lift knees to hip height alternating','Pump arms naturally with each step','Gradually increase knee height over 30 sec','Breathe steadily throughout'],
      why:'Raises heart rate gently and increases blood flow to lower body before cardio' },
    { name:'Jumping Jacks (slow)', duration:'30 reps',
      steps:['Start with feet together, arms at sides','Jump feet out while raising arms overhead','Return to start - controlled landing','Increase tempo after 10 warm-up reps'],
      why:'Full-body warmup that activates shoulders, core, hips and calves simultaneously' },
    { name:'High Knees (slow build)', duration:'30 sec',
      steps:['Jog in place lifting knees to hip height','Engage core - keep torso tall','Start slow, build pace over 30 seconds','Land softly on balls of feet'],
      why:'Activates hip flexors, calves and cardiovascular system progressively' },
  ],
}
